baseURL = "https://www.wangfenjin.com"
languageCode = "en-us"
title = "Wang Fenjin"
theme = "terminal"

[pagination]
  pagerSize = 10 # Sets 10 items per page

[params]
  contentTypeName = "posts"
  themeColor = "green"
  showMenuItems = 2
  fullWidthTheme = true
  centerTheme = true
  favicon = "favicon.ico"

[languages]
  [languages.en]
    title = "Wang Fenjin"
    subtitle = "Software Engineer at Bytedance"
    keywords = "software engineer, distributed system, storage system, golang, python, rust, c++"
    copyright = "Copyright Â© 2023 Wang Fenjin :: Powered by <a href=\"http://gohugo.io\">Hugo</a>"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Wang Fenjin's Blog"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 2
